### ISSUE TITLE
Username validation

### ISSUE THREAD

**Issue by alex-j-wang** [qiaochloe/bph-site#11]
https://github.com/qiaochloe/bph-site/blob/697408a0a8679568cbc91eb92b378d7c86a607d2/src/app/register/RegisterForm.tsx#L28

**Comment by alex-j-wang** [comment]
@JackSharks05 actually I don't think your changes got committed, the pull request you made only tried to pull changes for another issue from main into this branch

**Comment by JackSharks05** [comment]
.regex(/^[a-zA-Z0-9]*$/, { message: "String must contain only alphanumeric characters" }),

**Comment by JackSharks05** [comment]
this is weirdly out of sync but if someone can completely overwrite this with the current main that would be great and then i can insert the one line of code (above)

**Comment by alex-j-wang** [comment]
Branch should be up to date with main now, see if you can pull and then apply changes. Also might be worth looking into `\w` (which I think should be an abbreviation for your current expression).
