### ISSUE TITLE
Improve hint table formatting

### ISSUE THREAD

**Issue by alex-j-wang** [qiaochloe/bph-site#13]
https://github.com/qiaochloe/bph-site/blob/697408a0a8679568cbc91eb92b378d7c86a607d2/src/app/admin/components/HintTable.tsx#L33

**Comment by alex-j-wang** [comment]
Other changes:
- More prominent claim button
- Different style? new page or popout per hint?

**Comment by brian-xu** [comment]
- Use display names instead of database hashes for asking team/claimer
- Allow filter searchbox to search all fields (discord-style search as reach goal)
- Display conversation history/previous guesses in hinting page
