### ISSUE TITLE
Update page using hooks instead of refreshing

### ISSUE THREAD

**Issue by alex-j-wang** [qiaochloe/bph-site#9]
https://github.com/qiaochloe/bph-site/blob/697408a0a8679568cbc91eb92b378d7c86a607d2/src/app/login/LoginForm.tsx#L41

https://github.com/qiaochloe/bph-site/blob/697408a0a8679568cbc91eb92b378d7c86a607d2/src/app/admin/components/HintTable.tsx#L286

**Comment by qiaochloe** [comment]
Rethinking if this is needed. There are multiple ways to update the page (`useRouter`, `revalidatePath`, hooks, jQuery), and while hooks are more fine-grained than refreshing the page, they are more troublesome to work with.
