### ISSUE TITLE
Implement hint limits

### ISSUE THREAD

**Issue by guralpa** [qiaochloe/bph-site#92]

**Comment by qiaochloe** [comment]
From BPH 2024:

How do hints work?
Starting on Saturday, April 13, 2024, at 3:00 PM EDT, teams will gain one hint request every three hours, which they can use to ask for help on any puzzle.

You can use a hint to get help on a puzzle. This can be something like a nudge in the right direction (i.e. you give us your progress on the puzzle and we'll try to get you unstuck) or an answer to a question (e.g. “Which answers to these crossword clues are wrong?”).

If you are a beginner student team or a team with a strong on-site presence that is not in the running to win, we will also visit you frequently to check on your progress and help you along. If you are struggling, do not hesitate to reach out — the event is meant to be fun, and we want to ensure no hunter is left behind! If you want someone on HQ to come and visit you, you can email us at any time.

You can only have one open hint request at a time.
